sudo: false

language: bash

os:
  - linux

dist: focal

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
  - wget http://downloads.arduino.cc/arduino-1.8.13-linux64.tar.xz
  - tar xf arduino-1.8.13-linux64.tar.xz
  - mv arduino-1.8.13 $HOME/arduino_ide
  - cd $HOME/arduino_ide/hardware
  - mkdir esp32
  - cd esp32
  - wget https://github.com/espressif/arduino-esp32/archive/refs/tags/1.0.6.tar.gz
  - tar -xzf 1.0.6.tar.gz 
  - mv arduino-esp32-1.0.6/ esp32
  - cd esp32/tools
  - python --version
  - python get.py
  - pip install --user platformio
  - platformio update
  
script:
  - cd $TRAVIS_BUILD_DIR
  - export PATH="$HOME/arduino_ide:$PATH"
  - arduino --board esp32:esp32:esp32:PartitionScheme=huge_app,FlashFreq=80 --pref compiler.warning_level=all --save-prefs
  - arduino --verbose --verify esp32-cam-webserver.ino
  - cp --preserve --verbose myconfig.sample.h myconfig.h
  - arduino --verbose --verify esp32-cam-webserver.ino
  - platformio run

  
notifications:
  email:
    on_success: change
    on_failure: change

